image:
  repository: selcucommonacr.azurecr.io/selfcaremsnotificationmanager
  tag: 1.0-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://imprese.uat.notifichedigitali.it,https://pnpg.uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - uat01.pnpg.internal.uat.selfcare.pagopa.it
      secretName: uat01-pnpg-internal-uat-selfcare-pagopa-it
  hosts:
    - host: "uat01.pnpg.internal.uat.selfcare.pagopa.it"
      paths:
        - path: /ms-notification/v1/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_NOTIFICATION_MANAGER_LOG_LEVEL: "INFO"
  CUSTOMER_CARE_MAIL: "pectest@pec.pagopa.it"
  CUSTOMER_CARE_MAIL_SUBJECT_PREFIX: "[UAT] "
  NOTIFICATION_TO_USER_SUBJECT_PREFIX: "[SELF CARE UAT] "
  MAIL_CONNECTOR_TYPE: aws
  MAIL_SERVER_SMTP_AUTH: false