image:
  repository: selcpacr.azurecr.io/selfcaremsnotificationmanager
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 1.0-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"
  tls:
    - hosts:
        - selc.internal.selfcare.pagopa.it
      secretName: selc-internal-selfcare-pagopa-it
  hosts:
    - host: selc.internal.selfcare.pagopa.it
      paths:
        - path: /ms-notification-manager/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 2

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_NOTIFICATION_MANAGER_LOG_LEVEL: "INFO"
  CUSTOMER_CARE_MAIL: "areariservata@assistenza.pagopa.it"
  CUSTOMER_CARE_MAIL_SUBJECT_PREFIX: ""
  NOTIFICATION_TO_USER_SUBJECT_PREFIX: ""
  MAIL_CONNECTOR_TYPE: default