replicaCount: 2

image:
  repository: selcuacr.azurecr.io/selfcaremsnotificationmanager
  tag: 1.0-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.uat.selfcare.pagopa.it
      secretName: selc-internal-uat-selfcare-pagopa-it
  hosts:
    - host: selc.internal.uat.selfcare.pagopa.it
      paths:
        - path: /ms-notification-manager/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 200m
    memory: 500M
  limits:
    cpu: 500m
    memory: 600M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_NOTIFICATION_MANAGER_LOG_LEVEL: "INFO"
  CUSTOMER_CARE_MAIL: "pectest@pec.pagopa.it"
  CUSTOMER_CARE_MAIL_SUBJECT_PREFIX: "[UAT] "
  NOTIFICATION_TO_USER_SUBJECT_PREFIX: "[SELF CARE UAT] "
  MAIL_CONNECTOR_TYPE: aws