image:
  repository: selcdacr.azurecr.io/selfcaremsnotificationmanager

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_NOTIFICATION_MANAGER_LOG_LEVEL: "DEBUG"
  CUSTOMER_CARE_MAIL: "pectest@pec.pagopa.it"
  CUSTOMER_CARE_MAIL_SUBJECT_PREFIX: "[CUSTOMER CARE DEV] "
  NOTIFICATION_TO_USER_SUBJECT_PREFIX: "[SELF CARE DEV] "
