replicaCount: 2

image:
  repository: selcdacr.azurecr.io/selfcaremsnotificationmanager

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.dev.selfcare.pagopa.it
      secretName: selc-internal-dev-selfcare-pagopa-it
  hosts:
    - host: selc.internal.dev.selfcare.pagopa.it
      paths:
        - path: /ms-notification-manager/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 200m
    memory: 500M
  limits:
    cpu: 500m
    memory: 600M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_NOTIFICATION_MANAGER_LOG_LEVEL: "DEBUG"
  CUSTOMER_CARE_MAIL: "pectest@pec.pagopa.it"
  CUSTOMER_CARE_MAIL_SUBJECT_PREFIX: "[CUSTOMER CARE DEV] "
  NOTIFICATION_TO_USER_SUBJECT_PREFIX: "[SELF CARE DEV] "
  MAIL_CONNECTOR_TYPE: aws
