name: Create Release branch

on:
  workflow_dispatch:
    inputs:
      version-bump:
        required: false
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch
        description: 'Major, Minor, or Patch version bump'

jobs:
  create_branch:
    name: 'Create Release Branch'
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      actions: write

    steps:

      - name: Create Release Branch
        uses: pagopa/selfcare-commons/github-actions-template/create-release@create-release-action
        with:
          version_bump: ${{ inputs.version-bump }}

      - name: Trigger release ms UAT Release
        run: |
          gh workflow run release_ms.yml \
            --ref $NEW_BRANCH_NAME

      - name: Trigger PNPG release ms UAT Release
        run: |
          gh workflow run release_ms_pnpg.yml \
            --ref $NEW_BRANCH_NAME
