name: optic
on:
  pull_request:
  push:
    branches:
      - "test-optic"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
          name: Checkout
          with:
            fetch-depth: 0

        - name: Set up JDK 17
          uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

        - name: Build with Maven
          run: mvn test -Dtest=SwaggerConfigTest#swaggerSpringPlugin -DfailIfNoTests=false
 
        - name: Install Optic
          run: npm install --location global @useoptic/optic

        - name: Check Open API by Optic
          id: optic_diff
          run: optic diff app/src/main/resources/swagger/api-docs.json --base origin/main --check