name: optic
on:
  pull_request:
  push:
    branches:
      - "test-optic"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
          name: Checkout
          with:
            fetch-depth: 0
 
        - name: Install Optic
          run: npm install --location global @useoptic/optic

        - name: Run Optic
          id: optic_diff
          run: |
            OUTPUT=$(optic diff app/src/main/resources/swagger/api-docs.json --base origin/main)
            echo "$OUTPUT"
            echo "::set-output name=optic_output::$OUTPUT"