name: optic
on:
  pull_request:
  push:
    branches:
      - "test-optic"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Install Optic
        run: npm install --location global @useoptic/optic
 
      - name: Run Optic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: optic run