name: optic
on:
  pull_request:
  push:
    branches:
      - "test-optic"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Install Optic
        run: npm install --location global @useoptic/optic

      - name: Run Optic
        id: optic_diff
        run: |
            OUTPUT=$(optic diff app/src/main/resources/swagger/api-docs.json --base main --check)
            echo "$OUTPUT"
            echo "::set-output name=optic_output::$OUTPUT"