name: Release - ms-notification-manager

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

  push:
    branches:
      - main
      - releases/*
    paths:
      - '!.devops/**'
      - '!helm/**'
      - '!**.md'
      - '!**ignore'
      - '!infra/**'
      - '!.terraform-version'
      - '!CODEOWNERS'

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Dev] NotificationManager ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev
      dir: 'infra/container_apps'

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[UAT] NotificationManager ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat
      dir: 'infra/container_apps'

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Prod] NotificationManager ms Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod
      dir: 'infra/container_apps'

  promote_release:
    uses:  pagopa/selfcare-commons/github-actions-template/promote-release@ops/promote-release-action
    name: 'Promote prerelase release'
    needs: [release_prod]
    secrets: inherit
    with:
      github_path_token: ${{ secrets.GH_PAT_VARIABLES }}