name: Release PNPG ms-notification-manager

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - releases/*
    paths:
      - '!.devops/**'
      - '!helm/**'
      - '!**.md'
      - '!**ignore'
      - '!infra/**'
      - '!.terraform-version'
      - '!CODEOWNERS'

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@EC-149-template-git-hub-workflows
    name: '[Dev] NotificationManager ms Release'
    if: startsWith(github.ref_name, 'releases/') != true
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-pnpg
      dir: 'infra'

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@EC-149-template-git-hub-workflows
    name: '[UAT] NotificationManager ms Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: uat
      tf_environment: dev-pnpg
      dir: 'infra'

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@EC-149-template-git-hub-workflows
    name: '[Prod] NotificationManager ms Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: prod
      tf_environment: dev-pnpg
      dir: 'infra'